version: "3"
services:
  web:
    image: sregistry.azurecr.io/geoweb_server:1.10
    container_name: web_server
    environment:
      - ALLOW_OVERRIDE=true
    ports:
      - "8080:80"
    links:
      - mysql
    # networks:
    #   web_net:
    #     ipv4_address: 172.28.1.1


  mysql:
    image: sregistry.azurecr.io/mysql_server:1.10
    container_name: mysql_server
    restart: always
    ports:
      - "6379:6379"

    # networks:
    #   web_net:
    #     ipv4_address: 172.28.1.2

# networks:
#   web_net:
#     ipam:
#       driver: default
#       config:
#         - subnet: 172.28.0.0/16
